# --- Configurações Gerais de Tom e Estilo para Escrita Jurídica ---
# --- Valores adaptados para o Perfil: Parecerista Jurídico ---

# 1. Nucleo do Tom (Core Tone)
tone_core:
  formality_level: high # Mantido: Pareceres exigem alta formalidade, embora possam ser ligeiramente menos rígidos que sentenças, dependendo do destinatário.
  objectivity_bias: strong # Mantido: A análise deve ser objetiva e imparcial, baseada em fontes fidedignas (lei, doutrina, jurisprudência).
  persuasiveness_intent: low # Ajustado: O foco primário é a análise técnica e a exposição fundamentada de uma tese, não necessariamente persuadir a todo custo. Pode ser 'moderate' se o objetivo for defender uma interpretação específica. Assume-se 'low' para parecer técnico padrão.
  language_register: formal_legal # Mantido: O registro predominante ainda é o técnico-jurídico. Pode tender a 'technical_academic' em pareceres mais aprofundados.

# 2. Estrutura e Clareza (Structure & Clarity)
structure_style:
  conciseness_preference: balanced_detailed # Ajustado: Pareceres frequentemente exigem uma exploração mais exaustiva da questão, doutrina e jurisprudência, justificando um nível maior de detalhamento que uma sentença concisa.
  sentence_complexity: moderate # Mantido: A clareza ainda é crucial, mas a complexidade inerente aos temas jurídicos é mantida.
  paragraph_length: standard # Mantido: Estrutura de parágrafos padrão para boa organização das ideias.
  voice_preference: active # Mantido: Voz ativa priorizada para clareza, com uso funcional da passiva.

# 3. Terminologia e Citação (Terminology & Citation)
terminology_citation:
  jargon_usage: controlled # Ajustado: Uso de jargão técnico necessário, mas com potencial necessidade de explicações adicionais, dependendo da familiaridade do público-alvo com o tema.
  citation_style: abnt_simplified # Ajustado: Sugere-se um padrão comum para trabalhos técnicos/acadêmicos como ABNT (simplificado ou completo), mas pode ser adaptado (ex: 'specific_client_rule', 'iso_690'). Mantém a rastreabilidade das fontes.
  doctrine_reference_depth: detailed_discussion # Ajustado: Pareceres frequentemente se aprofundam na doutrina para embasar a análise. Discussão detalhada é mais comum que em sentenças.
  jurisprudence_integration: detailed_analysis # Mantido/Reforçado: Análise aprofundada da jurisprudência, possivelmente comparativa, é essencial para um parecer robusto.

# 4. Restrições e Elementos Proibidos (Constraints & Prohibitions)
constraints:
  avoid_contractions: true # Mantido.
  avoid_slang_colloquialisms: true # Mantido.
  avoid_emotional_language: true # Mantido: Impessoalidade e tecnicidade são chave.
  avoid_first_person_singular: moderate # Ajustado: Embora a impessoalidade seja preferível, o parecerista pode, com moderação, usar expressões como "entendo que", "parece-me que" ao expressar sua conclusão ou interpretação pessoal fundamentada.
  avoid_rhetorical_questions: none # Mantido: Foco na análise direta.

# 5. Audiência e Contexto (Audience & Context)
context_specifics:
  target_audience: specific_requester # Ajustado: O público é variável (cliente, gestor, outro advogado, órgão público). Deve ser definido caso a caso. Ex: 'internal_manager', 'external_client_non_lawyer', 'public_prosecutor'.
  document_type: legal_opinion # Ajustado: Define o propósito e estrutura esperada como um parecer jurídico.