# --- Configurações Gerais de Tom e Estilo para Escrita Jurídica ---

# 1. Nucleo do Tom (Core Tone)
tone_core:
  formality_level: high # Nível de formalidade. Opções: high (padrão), standard_legal, medium, low (evitar para peças formais).
  objectivity_bias: strong # Ênfase na neutralidade e fatos. Opções: strong, moderate, low (permitir mais subjetividade/opinião, se aplicável).
  persuasiveness_intent: moderate # Grau de intenção argumentativa. Opções: none (informativo), low (descritivo), moderate (fundamentação), high (petição/recurso).
  language_register: formal_legal # Registro linguístico. Opções: formal_legal, technical_academic, formal_administrative.

# 2. Estrutura e Clareza (Structure & Clarity)
structure_style:
  conciseness_preference: balanced # Preferência por brevidade vs. detalhamento. Opções: high (máxima concisão), balanced, detailed (explicativo).
  sentence_complexity: moderate # Complexidade sintática das frases. Opções: simple, moderate, complex (usar com cautela).
  paragraph_length: standard # Comprimento médio dos parágrafos. Opções: short, standard, long.
  voice_preference: active # Preferência pela voz verbal. Opções: active (preferencial para clareza), passive (permitido para ênfase específica/impessoalidade).

# 3. Terminologia e Citação (Terminology & Citation)
terminology_citation:
  jargon_usage: necessary # Uso de jargão técnico-jurídico. Opções: necessary (apenas o essencial), controlled (com explicações), extensive (para público especializado).
  citation_style: abnt_simplified # Estilo de citação preferido. Opções: abnt_full, abnt_simplified, specific_court_rule_[NomeTribunal], inline_simplified.
  doctrine_reference_depth: summary # Profundidade na referência à doutrina. Opções: none, mention, summary, detailed_discussion.
  jurisprudence_integration: key_holdings # Como integrar jurisprudência. Opções: mention_only, key_holdings, detailed_analysis, comparative.

# 4. Restrições e Elementos Proibidos (Constraints & Prohibitions)
constraints:
  avoid_contractions: true # Evitar contrações (ex: "não" em vez de "ñ"). Opções: true, false.
  avoid_slang_colloquialisms: true # Evitar gírias e linguagem coloquial. Opções: true, false.
  avoid_emotional_language: true # Evitar linguagem excessivamente emotiva ou subjetiva. Opções: true, false.
  avoid_first_person_singular: true # Evitar "Eu acho", "Na minha opinião". Opções: true (exceto em contextos específicos como votos), false.
  avoid_rhetorical_questions: moderate # Uso de perguntas retóricas. Opções: none, moderate, free.

# 5. Audiência e Contexto (Audience & Context)
context_specifics:
  target_audience: judge # Público principal do texto. Opções: judge, opposing_counsel, client, internal_team, general_public.
  document_type: decision_draft # Tipo de documento sendo gerado (influencia outras chaves). Opções: petition, decision_draft, sentence_draft, legal_opinion, internal_memo, case_summary.